# Database
spring:
  datasource:
    url: jdbc:postgresql://${NACHRICHTENSYSTEM_DB}:5432/${NACHRICHTENSYSTEM_DB_NAME}
    password: ${NACHRICHTENSYSTEM_DB_PW}
    username: ${NACHRICHTENSYSTEM_DB_USER}
  # kafka servers
  kafka:
    bootstrap-servers: kafka:9092

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/
    enabled: true
server:
  servlet:
    session:
      cookie:
        domain: localhost
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
# Test
enabled: false
