spring:
  datasource:
    url: jdbc:postgresql://${SHOP_DEMO_DB}:5432/${SHOP_DEMO_DB_NAME}
    password: ${SHOP_DEMO_DB_PW}
    username: ${SHOP_DEMO_DB_USER}
  # kafka servers
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/,http://eureka-2:8761/eureka/
