# Database
#spring:
#  datasource:
#    url: jdbc:postgresql://${SHOP_DEMO_DB}:5432/${SHOP_DEMO_DB_NAME}
#    password: ${SHOP_DEMO_DB_PW}
#    username: ${SHOP_DEMO_DB_USER}
#  # kafka servers
#  kafka:
#    bootstrap-servers: kafka:9092
#
## Eureka
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-1:8761/eureka/
#    enabled: true
server:
  servlet:
    session:
      cookie:
        domain: localhost
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
