version: "3.7"

services:
  postgres:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  springboot-service:
    image: docker.nexus.archi-lab.io/archilab/fae-team-3-service:${TAG}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - fae_backend

networks:
  fae_backend:
    external: true