version: "3.7"

services:
  springboot-service:
    image: docker.nexus.archi-lab.io/archilab/fae-team-3-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8081"
    networks:
      - fae_backend

networks:
  fae_backend:
    external: true